import type { Metadata } from "next";
import { arimo } from "../lib/fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={arimo.className}>{children}</body>
    </html>
  );
}
